import { inter } from '@/app/fonts'

// ...existing code...
<div className={`${inter.className} fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50`}>
      <div className="relative bg-white dark:bg-gray-800 p-6 rounded-lg shadow-lg w-full max-w-md">
// ...existing code...