import { Inter } from "next/font/google";
import "@/app/styles/globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/context/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Anita Gonzalez Gallery",
  description: "Generated by Mikauran",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body
          className={`${inter.className} bg-gray-50 dark:bg-gray-800 transition-colors duration-300`}
        >
          <Navbar />
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
