import { Inter } from "next/font/google";
import "@/app/styles/globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/context/ThemeContext";
import Copyright from "@/components/Copyright";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Anita Gonzalez Gallery",
  description: "Generated by Mikauran",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body
                    className={`${inter.className} bg-gray-50 dark:bg-gray-800 transition-colors 
                    duration-300 grid grid-rows-[auto_1fr_auto] min-h-screen`}
        >

          {/* Header */}
          <Navbar />

          {/* Main Content */}
          <main className="flex-grow">{children}</main>

          {/* Footer */}
          <Copyright />
        </body>
      </html>
    </ThemeProvider>
  );
}
