import { Inter } from "next/font/google";
import "@/app/styles/globals.css"
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Anita Gonzalez Gallery",
  description: "Generated by Mikauran",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

       {/*  <div className="min-h-screen bg-gray-50"> */}
          <Navbar/>
        {/* </div> */}

        {children}

       </body>
    </html>
  );
}
